// <auto-generated />
namespace Week32021ClubDomain.Classes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CLUBMODELADDED : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CLUBMODELADDED));
        
        string IMigrationMetadata.Id
        {
            get { return "202010151627328_CLUB MODEL ADDED"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
