// <auto-generated />
namespace RAD3012021Week4.ClubDomain.Classes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CLUBCONTEXTSETUP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CLUBCONTEXTSETUP));
        
        string IMigrationMetadata.Id
        {
            get { return "202010230946090_CLUB CONTEXT SETUP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
