// <auto-generated />
namespace RAD3012021Week4.MVCClub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class forgottoaddrolesforradp2016outlookcom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(forgottoaddrolesforradp2016outlookcom));
        
        string IMigrationMetadata.Id
        {
            get { return "202011061954582_forgot to add roles for radp2016@outlook.com"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
