// <auto-generated />
namespace Week32021MVCClub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class INITIALMIGRATIONUSERDATABASESETUP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(INITIALMIGRATIONUSERDATABASESETUP));
        
        string IMigrationMetadata.Id
        {
            get { return "202010140908409_INITIAL MIGRATION USER DATABASE SETUP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
