// <auto-generated />
namespace Week32021MVCClub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class triedseedingagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(triedseedingagain));
        
        string IMigrationMetadata.Id
        {
            get { return "202010311754250_tried seeding again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
